# Generated by Django 4.1.7 on 2023-02-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_and_surname', models.CharField(max_length=50, verbose_name='name_and_surname')),
                ('group', models.CharField(max_length=50, verbose_name='group')),
                ('gpa', models.FloatField(verbose_name='gpa')),
                ('attendance', models.CharField(max_length=50, verbose_name='attendace')),
            ],
        ),
    ]
